export const NIM_CONTROL_PLANE_HOST_ENV = 'HARNESS_NIM_CONTROL_PLANE_HOST';
export const NIM_CONTROL_PLANE_PORT_ENV = 'HARNESS_NIM_CONTROL_PLANE_PORT';
export const NIM_CONTROL_PLANE_AUTH_TOKEN_ENV = 'HARNESS_NIM_CONTROL_PLANE_AUTH_TOKEN';
