export const MUX_GLOBAL_SHORTCUT_ACTION_ORDER = [
  'mux.app.quit',
  'mux.app.interrupt-all',
  'mux.command-menu.toggle',
  'mux.debug-bar.toggle',
  'mux.gateway.profile.toggle',
  'mux.gateway.status-timeline.toggle',
  'mux.gateway.render-trace.toggle',
  'mux.conversation.new',
  'mux.conversation.critique.open-or-create',
  'mux.conversation.next',
  'mux.conversation.previous',
  'mux.conversation.titles.refresh-all',
  'mux.conversation.interrupt',
  'mux.conversation.archive',
  'mux.conversation.takeover',
  'mux.conversation.delete',
  'mux.directory.add',
  'mux.directory.close',
] as const;

export type MuxGlobalShortcutAction = (typeof MUX_GLOBAL_SHORTCUT_ACTION_ORDER)[number];

export const DEFAULT_MUX_SHORTCUT_BINDINGS_RAW: Readonly<
  Record<MuxGlobalShortcutAction, readonly string[]>
> = {
  'mux.app.quit': [],
  'mux.app.interrupt-all': ['ctrl+c'],
  'mux.command-menu.toggle': ['ctrl+p', 'cmd+p'],
  'mux.debug-bar.toggle': [],
  'mux.gateway.profile.toggle': ['ctrl+shift+p'],
  'mux.gateway.status-timeline.toggle': ['alt+r'],
  'mux.gateway.render-trace.toggle': ['ctrl+]'],
  'mux.conversation.new': ['ctrl+t'],
  'mux.conversation.critique.open-or-create': ['ctrl+g'],
  'mux.conversation.next': ['ctrl+j'],
  'mux.conversation.previous': ['ctrl+k'],
  'mux.conversation.titles.refresh-all': ['ctrl+r'],
  'mux.conversation.interrupt': [],
  'mux.conversation.archive': [],
  'mux.conversation.takeover': ['ctrl+l'],
  'mux.conversation.delete': ['ctrl+x'],
  'mux.directory.add': ['ctrl+o'],
  'mux.directory.close': ['ctrl+w'],
};

export const TASK_SCREEN_KEYBINDING_ACTION_ORDER = [
  'mux.home.repo.dropdown.toggle',
  'mux.home.repo.next',
  'mux.home.repo.previous',
  'mux.home.task.submit',
  'mux.home.task.queue',
  'mux.home.task.newline',
  'mux.home.task.status.ready',
  'mux.home.task.status.draft',
  'mux.home.task.status.complete',
  'mux.home.task.reorder.up',
  'mux.home.task.reorder.down',
  'mux.home.editor.cursor.left',
  'mux.home.editor.cursor.right',
  'mux.home.editor.cursor.up',
  'mux.home.editor.cursor.down',
  'mux.home.editor.line.start',
  'mux.home.editor.line.end',
  'mux.home.editor.word.left',
  'mux.home.editor.word.right',
  'mux.home.editor.delete.backward',
  'mux.home.editor.delete.forward',
  'mux.home.editor.delete.word.backward',
  'mux.home.editor.delete.line.start',
  'mux.home.editor.delete.line.end',
] as const;

export type TaskScreenKeybindingAction = (typeof TASK_SCREEN_KEYBINDING_ACTION_ORDER)[number];

export const DEFAULT_TASK_SCREEN_KEYBINDINGS_RAW: Readonly<
  Record<TaskScreenKeybindingAction, readonly string[]>
> = {
  'mux.home.repo.dropdown.toggle': ['alt+g'],
  'mux.home.repo.next': ['ctrl+n'],
  'mux.home.repo.previous': ['ctrl+p'],
  'mux.home.task.submit': ['enter'],
  'mux.home.task.queue': ['tab'],
  'mux.home.task.newline': ['shift+enter'],
  'mux.home.task.status.ready': ['alt+r'],
  'mux.home.task.status.draft': ['alt+d'],
  'mux.home.task.status.complete': ['alt+c'],
  'mux.home.task.reorder.up': ['ctrl+up'],
  'mux.home.task.reorder.down': ['ctrl+down'],
  'mux.home.editor.cursor.left': ['left', 'ctrl+b'],
  'mux.home.editor.cursor.right': ['right', 'ctrl+f'],
  'mux.home.editor.cursor.up': ['up'],
  'mux.home.editor.cursor.down': ['down'],
  'mux.home.editor.line.start': ['ctrl+a', 'home'],
  'mux.home.editor.line.end': ['ctrl+e', 'end'],
  'mux.home.editor.word.left': ['alt+b'],
  'mux.home.editor.word.right': ['alt+f'],
  'mux.home.editor.delete.backward': ['backspace'],
  'mux.home.editor.delete.forward': ['delete'],
  'mux.home.editor.delete.word.backward': ['ctrl+w', 'alt+backspace'],
  'mux.home.editor.delete.line.start': ['ctrl+u'],
  'mux.home.editor.delete.line.end': ['ctrl+k'],
};
